### ISSUE TITLE
No combined file generated

### ISSUE THREAD

**Issue by czery** [Lorti/grunt-svg-symbols#4]
Hi there, 

thanks for this plugin, it is exactly what I do need. I like the simplicity of SVG symbols and of referencing them in the markup.

I have a problem with this plugin though, it wouldn't export a sprite SVG file. I defined the task exactly like in your examples:

`svg_symbols: {
            options: {
                precision: 3,
                className: 'u-hidden',
                width: 24,
                height: 24
            },
            files: {
                'icons.svg': ['svg/**/*.svg']
            }
        }`

The task runs without errors but I do not receive an icons.svg as an output (searched the whole system for it :)) Do you have a clue where this issue comes from?

Cheers
czery

**Comment by Lorti** [comment]
Hi czery,

thank you for your feedback! Turns out I never tested the plugin when writing into the project root next to the Gruntfile.js (my bad, the case just never occurred in our usage...). I have added a test for it and it should be fixed in 0.1.20. Let me know if you have any further troubles!

**Comment by czery** [comment]
Hi Lorti,

thanks for your quick reaction and the plugin update. Unfortunately I still do not get any file when running the task above. Did I get the idea of the plugin right, that it generates the combined SVG file in the specified path (in my case project root level) or do I have to pipe the output from the plugin into a file on my own?

Cheers
czery

**Comment by Lorti** [comment]
Your config seems to be correct. Have you updated by running `npm install grunt-svg-symbols@latest` to be sure you are on 0.1.20? 

You should also have a look at your globbing pattern and if it really returns files. **Grunt tends to continue silently if there are no files found.** If you can share your code I could also try to reproduce the problem on my machine (at least the folder structure and the SVG files, if you don't want to share the rest).

**Comment by czery** [comment]
Yes, have updated to the latest version of your plugin. Also the globbing pattern does not seem to be the issue here. 

Attached you will find my test setup, would be awesome if you could test if you run into the error as well. 
[Archiv.zip](https://github.com/Lorti/grunt-svg-symbols/files/214510/Archiv.zip)

**Comment by Lorti** [comment]
Hi czery, seems that you have not specified a task name in your config. It is needed as `grunt-svg-symbols` is what they call a "multi task."
http://gruntjs.com/configuring-tasks#task-configuration-and-targets

```
svg_symbols: {
    some_task_name: {
        options: {
            ...
```

**Comment by czery** [comment]
Awesome, that fixed it. My bad.... Is this a thing to update in the example on this repo or does it work like in the example in other situations. 

Thanks a lot for your effort and thanks again for a great plugin.

Cheers
czery

**Comment by Lorti** [comment]
Oh, I see, I just used the example in the plugin boilerplate and didn't think about it, my bad. Thanks for telling, I will update it! :smile:
